version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    ports:
      - "5430:5432"
  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - ./config/victoria-metrics/promscrape.yaml:/promscrape.yaml
    ports:
      - "8428:8428"
  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.4
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - '3100:3100'

  # Сервис для разворачивания контейнера с приложением
#  webapi:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    hostname: webapi
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/wallet
#      - POSTGRES_USER=wallet
#      - POSTGRES_PASSWORD=wallet
#    healthcheck:
#      test: curl http://localhost:8080 || exit 0
#      interval: 10s
#      retries: 5
#      start_period: 15s
#      timeout: 10s